### ISSUE TITLE
Should we launch live version of mappypals, through github pages, or heroku?

### ISSUE THREAD

**Issue by ArnasDickus** [zero-to-mastery/mappypals#98]
So SeniorMan on discord had an idea of launching a master version of the project, through GitHub pages or Heroku. 

What's the purpose of it?
1) To allow the contributor to show a working version of the project, to the future employer, friends, etc.
2) Easier to detect bugs, when anyone can visit your site and look through instead of going to the master branch and writing `npm start`.

Options:
1) Launching live version front-end only on GitHub pages. The GitHub pages don't handle well with routing, so it would require some changes, using these tutorials:
[tutorial 1](https://levelup.gitconnected.com/deploying-a-create-react-app-with-routing-to-github-pages-f386b6ce84c2 )
[tutorial 2](https://medium.com/@Dragonza/react-router-problem-with-gh-pages-c93a5e243819)

2) Launching a full live version on Heroku. I know that Heroku supports node.js, but it could provide trouble to make it work front-end and back-end.

So what do you think? 
1) Should we try to launch the live version of the master branch?
2) How do we launch it, using GitHub pages, Heroku or something else entirely?

**Comment by fuckupc** [comment]
What's the potential problem with Heroku? I thought they support well with both front-end and back-end.

**Comment by ArnasDickus** [comment]
@fuckupc Somehow I missed your comment. Anyways the potential problem would be is to make it work with 2 repositories. I never tried it, so I think it's going to be tricky.

**Comment by ArnasDickus** [comment]
Talked with @mubarakshow he said that, we should try to launch it through Heroku.

**Comment by ArnasDickus** [comment]
Since the decision was made to launch on Heroku. I think this issue is solved.
